=== shawnphoffman/star-wars-codex-data/schema/collection.schema.json
{
  "$id": "https://star-wars-codex-data/schema/collection.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "collectionType": {
      "enum": [
        "tradePaperback",
        "omnibus",
        "hardcover",
        "treasuryEdition",
        "other"
      ],
      "type": "string"
    },
    "collects": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "era": {
      "type": "string"
    },
    "releaseDate": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "collectionType",
    "canonStatus"
  ],
  "title": "Collection",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_star-wars-crimson-reign_668.json
{
  "canonStatus": "canon",
  "collectionType": "hardcover",
  "collects": [
    "bounty-hunters-18",
    "bounty-hunters-19",
    "bounty-hunters-20",
    "bounty-hunters-21",
    "bounty-hunters-22",
    "bounty-hunters-23",
    "bounty-hunters-24",
    "crimson-reign-1",
    "crimson-reign-2",
    "crimson-reign-3",
    "crimson-reign-4",
    "crimson-reign-5"
  ],
  "displayTitle": "Crimson Reign",
  "slug": "c_star-wars-crimson-reign_668",
  "synopsis": "collects Star Wars: Crimson Reign (2021) #1-5, Star Wars (2020) #19-25, Star Wars: Bounty Hunters (2020) #18-24, Star Wars: Darth Vader (2020) #18-24, and Star Wars: Doctor Aphra (2020) #16-21.",
  "title": "Star Wars: Crimson Reign"
}
