=== shawnphoffman/star-wars-codex-data/schema/work.schema.json
{
  "$id": "https://star-wars-codex-data/schema/work.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "bookType": {
      "type": "string"
    },
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "creators": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "editionIds": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "type": {
            "enum": [
              "isbn13",
              "isbn10",
              "asin",
              "audibleAsin",
              "upc",
              "diamondCode"
            ],
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "value"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "editions": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "asin": {
            "type": "string"
          },
          "audibleAsin": {
            "type": "string"
          },
          "extent": {
            "type": "number"
          },
          "imprint": {
            "type": "string"
          },
          "isPrimary": {
            "type": "boolean"
          },
          "isbn10": {
            "type": "string"
          },
          "isbn13": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "print",
              "ebook",
              "audio"
            ],
            "type": "string"
          },
          "onsale": {
            "type": "string"
          },
          "upc": {
            "type": "string"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "era": {
      "type": "string"
    },
    "format": {
      "type": "string"
    },
    "inUniverseDate": {
      "additionalProperties": false,
      "properties": {
        "endYear": {
          "type": "integer"
        },
        "startYear": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "movie": {
      "additionalProperties": false,
      "properties": {
        "movieType": {
          "type": "string"
        },
        "mpaaRating": {
          "type": "string"
        },
        "runtimeMinutes": {
          "type": "number"
        },
        "subtitle": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "parentWorkSlug": {
      "type": "string"
    },
    "periodical": {
      "additionalProperties": false,
      "properties": {
        "imprint": {
          "type": "string"
        },
        "pageCount": {
          "type": "number"
        },
        "publicationKind": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "relatedWorkSlugs": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "releaseDate": {
      "type": "string"
    },
    "releaseDisplayState": {
      "type": "string"
    },
    "releaseStatus": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "format",
    "canonStatus",
    "releaseDisplayState"
  ],
  "title": "Work",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/choose-your-own-star-wars-adventure-a-new-hope.json
{
  "bookType": "juniorReader",
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Christopher Golden",
      "role": "writer",
      "slug": "christopher-golden"
    },
    {
      "name": "Eric Cherry",
      "role": "artist",
      "slug": "eric-cherry"
    }
  ],
  "displayTitle": "Choose Your Own Star Wars Adventure: A New Hope",
  "editions": [
    {
      "imprint": "Bantam Skylark",
      "isPrimary": true,
      "kind": "print",
      "onsale": "1998-05-09T00:00:00.000Z"
    }
  ],
  "format": "book",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1998-05-09T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "choose-your-own-star-wars-adventure-a-new-hope",
  "title": "Choose Your Own Star Wars Adventure: A New Hope"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/jabba-the-hutt-the-garr-suppoon-hit.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Jim Woodring",
      "role": "writer",
      "slug": "jim-woodring"
    },
    {
      "name": "Art Wetherell",
      "role": "penciler",
      "slug": "art-wetherell"
    },
    {
      "name": "Monty Sheldon",
      "role": "inker",
      "slug": "monty-sheldon"
    },
    {
      "name": "James Sinclair",
      "role": "colorist",
      "slug": "james-sinclair"
    },
    {
      "name": "Steve Dutro",
      "role": "letterer",
      "slug": "steve-dutro"
    },
    {
      "name": "Ryder Windham",
      "role": "editor",
      "slug": "ryder-windham"
    },
    {
      "name": "Scott Tice",
      "slug": "scott-tice"
    },
    {
      "name": "Steve Bissette",
      "role": "coverArtist",
      "slug": "steve-bissette"
    },
    {
      "name": "Cam Kennedy",
      "role": "coverArtist",
      "slug": "cam-kennedy"
    }
  ],
  "displayTitle": "Jabba the Hutt: The Garr Suppoon Hit",
  "format": "periodicalIssue",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1995-04-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "jabba-the-hutt-the-garr-suppoon-hit",
  "synopsis": "Jabba the Hutt lives to negotiate, and the art of the deal is his only discipline. But the goods he trades are the lives of others, and in that line of business you can't lose your head. In this self-contained story, Jabba finds himself bartering with Garr Suppoon, rumored to be an absolute devil at the negotiating table. There's a valuable lesson to be learned here: In a deal with the devil, you can always refuse. In a deal with Jabba, it's not advised.",
  "title": "Jabba the Hutt: The Garr Suppoon Hit"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-insider-insider-188.json
{
  "canonStatus": "canon",
  "displayTitle": "Insider #188",
  "format": "periodicalIssue",
  "parentWorkSlug": "star-wars-insider",
  "periodical": {
    "publicationKind": "magazine",
    "type": "singleIssue"
  },
  "releaseDisplayState": "announced",
  "slug": "star-wars-insider-insider-188",
  "title": "Insider #188"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-adventures-2017-27-ghosts-of-kashyyyk-part-1.json
{
  "canonStatus": "canon",
  "displayTitle": "Adventures (2017) #27 - Ghosts Of Kashyyyk part 1",
  "era": "riseOfTheFirstOrder",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 34
  },
  "parentWorkSlug": "star-wars-adventures-2017",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2019-10-28T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-adventures-2017-27-ghosts-of-kashyyyk-part-1",
  "title": "Star Wars Adventures (2017) #27 - Ghosts Of Kashyyyk part 1"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/return-of-the-jedi-the-special-edition.json
{
  "bookType": "graphicNovel",
  "canonStatus": "canon",
  "displayTitle": "Return of the Jedi: The Special Edition",
  "format": "book",
  "releaseDisplayState": "announced",
  "slug": "return-of-the-jedi-the-special-edition",
  "synopsis": "The trilogy aimed to renew the movies in the minds of both the older and the younger audience, and to prepare the way for the upcoming release of Star Wars: Episode I The Phantom Menace.",
  "title": "Return of the Jedi: The Special Edition"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/galaxy-of-fear-1997-9.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "John Whitman",
      "role": "writer",
      "slug": "john-whitman"
    }
  ],
  "displayTitle": "Galaxy of Fear #9: Spore",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 1
  },
  "parentWorkSlug": "galaxy-of-fear-1997",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1998-03-09T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "galaxy-of-fear-1997-9",
  "title": "Galaxy of Fear #9: Spore"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/phasma.json
{
  "bookType": "adultNovel",
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Delilah S. Dawson",
      "role": "writer",
      "slug": "delilah-s-dawson"
    },
    {
      "name": "Larry Rostant",
      "role": "coverArtist",
      "slug": "larry-rostant"
    }
  ],
  "displayTitle": "Phasma",
  "editionIds": [
    {
      "type": "isbn10",
      "value": "1524796336"
    },
    {
      "type": "isbn13",
      "value": "9781524796310"
    },
    {
      "type": "isbn13",
      "value": "9781524796334"
    }
  ],
  "editions": [
    {
      "extent": 380,
      "imprint": "Del Rey",
      "isPrimary": false,
      "isbn13": "9781524796310",
      "kind": "print",
      "onsale": "2017-09-01T00:00:00.000Z"
    },
    {
      "extent": 380,
      "imprint": "Del Rey",
      "isPrimary": true,
      "isbn10": "1524796336",
      "isbn13": "9781524796334",
      "kind": "print",
      "onsale": "2017-09-01T00:00:00.000Z"
    }
  ],
  "era": "riseOfTheFirstOrder",
  "format": "book",
  "inUniverseDate": {
    "endYear": 34,
    "startYear": 22
  },
  "releaseDate": "2017-09-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "phasma",
  "synopsis": "When a First Order ship crash-lands on a remote world, a determined warrior discovers she doesn't just want to help the survivors. She wants to become one of them.",
  "title": "Phasma"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/ghosts-of-vaders-castle-2.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Cavan Scott",
      "role": "writer",
      "slug": "cavan-scott"
    },
    {
      "name": "Francesco Francavilla",
      "role": "artist",
      "slug": "francesco-francavilla"
    },
    {
      "name": "Derek Charm",
      "role": "artist",
      "slug": "derek-charm"
    }
  ],
  "displayTitle": "Ghosts of Vader's Castle #2",
  "era": "ageOfRebellion",
  "format": "periodicalIssue",
  "parentWorkSlug": "ghosts-of-vaders-castle",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2021-09-29T00:00:00.000Z",
  "releaseDisplayState": "upcoming",
  "slug": "ghosts-of-vaders-castle-2",
  "synopsis": "The epic five week event miniseries Star Wars Adventures: Ghosts of Vader's Castle continues!\nIn issue #2, Lina searches for the now missing Milo and Crater and runs into... Jaxxon! He reveals that he, too, has been having nightmares, but of vicious Wookiees bigger than mountains! It seems the GHOSTS OF VADER'S CASTLE are haunting everyone's dreams…",
  "title": "Ghosts of Vader's Castle #2"
}
