=== shawnphoffman/star-wars-codex-data/schema/work.schema.json
{
  "$id": "https://star-wars-codex-data/schema/work.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "bookType": {
      "type": "string"
    },
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "creators": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "editionIds": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "type": {
            "enum": [
              "isbn13",
              "isbn10",
              "asin",
              "audibleAsin",
              "upc",
              "diamondCode"
            ],
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "value"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "editions": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "asin": {
            "type": "string"
          },
          "audibleAsin": {
            "type": "string"
          },
          "extent": {
            "type": "number"
          },
          "imprint": {
            "type": "string"
          },
          "isPrimary": {
            "type": "boolean"
          },
          "isbn10": {
            "type": "string"
          },
          "isbn13": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "print",
              "ebook",
              "audio"
            ],
            "type": "string"
          },
          "onsale": {
            "type": "string"
          },
          "upc": {
            "type": "string"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "era": {
      "type": "string"
    },
    "format": {
      "type": "string"
    },
    "inUniverseDate": {
      "additionalProperties": false,
      "properties": {
        "endYear": {
          "type": "integer"
        },
        "startYear": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "movie": {
      "additionalProperties": false,
      "properties": {
        "movieType": {
          "type": "string"
        },
        "mpaaRating": {
          "type": "string"
        },
        "runtimeMinutes": {
          "type": "number"
        },
        "subtitle": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "parentWorkSlug": {
      "type": "string"
    },
    "periodical": {
      "additionalProperties": false,
      "properties": {
        "imprint": {
          "type": "string"
        },
        "pageCount": {
          "type": "number"
        },
        "publicationKind": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "relatedWorkSlugs": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "releaseDate": {
      "type": "string"
    },
    "releaseDisplayState": {
      "type": "string"
    },
    "releaseStatus": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "format",
    "canonStatus",
    "releaseDisplayState"
  ],
  "title": "Work",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/darth-vader-2020-06.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Greg Pak",
      "role": "writer",
      "slug": "greg-pak"
    },
    {
      "name": "Raffaele Ienco",
      "role": "artist",
      "slug": "raffaele-ienco"
    },
    {
      "name": "Mark Paniccia",
      "role": "editor",
      "slug": "mark-paniccia"
    },
    {
      "name": "Joe Caramagna",
      "role": "letterer",
      "slug": "joe-caramagna"
    },
    {
      "name": "Raffaele Ienco",
      "role": "inker",
      "slug": "raffaele-ienco"
    },
    {
      "name": "Raffaele Ienco",
      "role": "penciler",
      "slug": "raffaele-ienco"
    },
    {
      "name": "In-Hyuk Lee",
      "role": "coverArtist",
      "slug": "in-hyuk-lee"
    },
    {
      "name": "Neeraj Menon",
      "role": "colorist",
      "slug": "neeraj-menon"
    }
  ],
  "displayTitle": "Darth Vader (2020) #06",
  "era": "ageOfRebellion",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 3
  },
  "parentWorkSlug": "darth-vader-2020",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2020-10-14T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "darth-vader-2020-06",
  "synopsis": "Darth Vader failed to turn his son, Luke Skywalker, to the dark side of the Force.\n\nNo...Luke was too weak to join his father in overthrowing Emperor Palpatine.\n\nVader sought revenge against those who hid Luke from him for all of these years, and in doing so nearly betrayed his master. It did not go unnoticed by Palpatine... time for Vader's next lesson.",
  "title": "Darth Vader (2020) #06"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/darth-vader-and-the-ghost-prison-2.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "W. Haden Blackman",
      "role": "writer",
      "slug": "w-haden-blackman"
    },
    {
      "name": "Michael Heisler",
      "role": "colorist",
      "slug": "michael-heisler"
    },
    {
      "name": "Agustin Alessio",
      "role": "inker",
      "slug": "agustin-alessio"
    },
    {
      "name": "Agustin Alessio",
      "role": "letterer",
      "slug": "agustin-alessio"
    },
    {
      "name": "Agustin Alessio",
      "role": "penciler",
      "slug": "agustin-alessio"
    },
    {
      "name": "Agustin Alessio",
      "role": "artist",
      "slug": "agustin-alessio"
    },
    {
      "name": "Dave Wilkins",
      "role": "coverArtist",
      "slug": "dave-wilkins"
    }
  ],
  "displayTitle": "Darth Vader and the Ghost Prison #2",
  "era": "fallOfTheJedi",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": -19
  },
  "parentWorkSlug": "darth-vader-and-the-ghost-prison-graphic-novel",
  "periodical": {
    "pageCount": 32,
    "publicationKind": "comic"
  },
  "releaseDate": "2012-06-20T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "darth-vader-and-the-ghost-prison-2",
  "synopsis": "Graduating cadet Tohm’s first night as an Imperial officer has already seen him assisting Darth Vader in fighting a traitorous uprising, saving Emperor Palpatine from a deadly plague weapon, and keeping the peace between Vader and the cybernetic Moff Trachta. Now Tohm and Vader have infiltrated the deathly stillness of the abandoned Jedi Temple to confront the secrets of Vader’s past, and to learn the facts about the Ghost Prison! * An Imperial cadet fights at the side of the Dark Lord! * A brand-new series by Haden Blackman!",
  "title": "Darth Vader and the Ghost Prison #2"
}

=== shawnphoffman/star-wars-codex-data/data/works/tv-episode/young-jedi-adventures-s2e41.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Casey Lowe",
      "role": "director",
      "slug": "casey-lowe"
    },
    {
      "name": "Christian Streaty",
      "role": "writer",
      "slug": "christian-streaty"
    }
  ],
  "displayTitle": "Fossil Hunt",
  "era": "highRepublic",
  "format": "tvEpisode",
  "parentWorkSlug": "young-jedi-adventures-s2",
  "releaseDate": "2025-05-09T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "young-jedi-adventures-s2e41",
  "synopsis": "\"Fossil Hunt\" is the second part of the twenty-first episode of the second season the animated series Star Wars: Young Jedi Adventures. It was released on Disney+ on March 19, 2025.",
  "title": "Fossil Hunt"
}

=== shawnphoffman/star-wars-codex-data/data/works/tv-series/disney-gallery-the-mandalorian.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Jon Favreau",
      "role": "producer",
      "slug": "jon-favreau"
    },
    {
      "name": "Kathleen Kennedy",
      "role": "producer",
      "slug": "kathleen-kennedy"
    },
    {
      "name": "Dave Filoni",
      "role": "producer",
      "slug": "dave-filoni"
    },
    {
      "name": "Bradford Baruh",
      "role": "producer",
      "slug": "bradford-baruh"
    },
    {
      "name": "Karen Gilchrist",
      "role": "producer",
      "slug": "karen-gilchrist"
    },
    {
      "name": "John Bartnicki",
      "role": "producer",
      "slug": "john-bartnicki"
    },
    {
      "name": "Michael Kramer",
      "role": "composer",
      "slug": "michael-kramer"
    }
  ],
  "displayTitle": "Disney Gallery: The Mandalorian",
  "format": "tvSeries",
  "releaseDate": "2020-05-04T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "disney-gallery-the-mandalorian",
  "title": "Disney Gallery: The Mandalorian"
}

=== shawnphoffman/star-wars-codex-data/data/works/tv-episode/star-wars-droids-tv-series-season-1-s01-star-wars-droids-tv-series-s01e10.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Ken Stephenson",
      "role": "director",
      "slug": "ken-stephenson"
    },
    {
      "name": "Ben Burtt",
      "role": "writer",
      "slug": "ben-burtt"
    },
    {
      "name": "Michael Reaves",
      "role": "writer",
      "slug": "michael-reaves"
    }
  ],
  "displayTitle": "Tail of the Roon Comets",
  "format": "tvEpisode",
  "parentWorkSlug": "star-wars-droids-tv-series-season-1-s01",
  "releaseDate": "1985-11-09T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-droids-tv-series-season-1-s01-star-wars-droids-tv-series-s01e10",
  "synopsis": "R2-D2, C-3PO and Mungo Baobab are captured by the Empire on the way to the Roon system.",
  "title": "Tail of the Roon Comets"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical/thrawn-the-manga.json
{
  "canonStatus": "canon",
  "displayTitle": "Thrawn: The Manga",
  "format": "periodical",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2026-09-29T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "thrawn-the-manga",
  "title": "Thrawn: The Manga"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/star-wars-the-making-of-the-movie.json
{
  "bookType": "childrensBook",
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Larry Weinberg",
      "role": "writer",
      "slug": "larry-weinberg"
    }
  ],
  "displayTitle": "The Making of the Movie",
  "editions": [
    {
      "imprint": "Random House",
      "isPrimary": true,
      "kind": "print",
      "onsale": "1980-09-06T00:00:00.000Z"
    }
  ],
  "format": "book",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1980-09-06T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-the-making-of-the-movie",
  "synopsis": "Star Wars: The Making of the Movie was a children's book published in September 1980 by Random House as part of the \"Step-Up Books\" series and written by Larry Weinberg. The cover price was $4.95.The book gave children a behind-the-scenes look at the making of Star Wars: Episode IV A New Hope, and also retold the story of the film.",
  "title": "Star Wars: The Making of the Movie"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical/infinities-esb.json
{
  "bookType": "other",
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Dave Land",
      "role": "writer",
      "slug": "dave-land"
    },
    {
      "name": "Davidé Fabbri",
      "role": "penciler",
      "slug": "david-fabbri"
    },
    {
      "name": "Christian Dalla Vecchia",
      "role": "inker",
      "slug": "christian-dalla-vecchia"
    },
    {
      "name": "Dan Jackson",
      "role": "colorist",
      "slug": "dan-jackson"
    },
    {
      "name": "Steve Dutro",
      "role": "letterer",
      "slug": "steve-dutro"
    },
    {
      "name": "Chris Bachalo",
      "role": "coverArtist",
      "slug": "chris-bachalo"
    }
  ],
  "displayTitle": "Infinities: The Empire Strikes Back",
  "era": "multiEra",
  "format": "periodical",
  "periodical": {
    "imprint": "Dark Horse Comics",
    "publicationKind": "comic"
  },
  "releaseDate": "2002-07-10T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "infinities-esb",
  "synopsis": "Take the events and characters from one of the classic Star Wars films, throw in one happenstance, mishap, or technical glitch beyond the characters' control, and watch how that changes everything. In Dark Horse's first foray into Infinities (Star Wars Infinities: A New Hope), Luke Skywalker's valiant torpedo attack on the Death Star failed due to a faulty detonator -- an event no one could have foreseen -- and the Rebellion was dealt a debilitating setback. In Infinities -- The Empire Strikes Back, Han Solo's desperate attempt to locate his friend Luke in the icy wastes of the planet Hoth is ",
  "title": "Star Wars Infinities: The Empire Strikes Back"
}
