=== shawnphoffman/star-wars-codex-data/schema/work.schema.json
{
  "$id": "https://star-wars-codex-data/schema/work.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "bookType": {
      "type": "string"
    },
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "creators": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "editionIds": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "type": {
            "enum": [
              "isbn13",
              "isbn10",
              "asin",
              "audibleAsin",
              "upc",
              "diamondCode"
            ],
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "value"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "editions": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "asin": {
            "type": "string"
          },
          "audibleAsin": {
            "type": "string"
          },
          "extent": {
            "type": "number"
          },
          "imprint": {
            "type": "string"
          },
          "isPrimary": {
            "type": "boolean"
          },
          "isbn10": {
            "type": "string"
          },
          "isbn13": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "print",
              "ebook",
              "audio"
            ],
            "type": "string"
          },
          "onsale": {
            "type": "string"
          },
          "upc": {
            "type": "string"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "era": {
      "type": "string"
    },
    "format": {
      "type": "string"
    },
    "inUniverseDate": {
      "additionalProperties": false,
      "properties": {
        "endYear": {
          "type": "integer"
        },
        "startYear": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "movie": {
      "additionalProperties": false,
      "properties": {
        "movieType": {
          "type": "string"
        },
        "mpaaRating": {
          "type": "string"
        },
        "runtimeMinutes": {
          "type": "number"
        },
        "subtitle": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "parentWorkSlug": {
      "type": "string"
    },
    "periodical": {
      "additionalProperties": false,
      "properties": {
        "imprint": {
          "type": "string"
        },
        "pageCount": {
          "type": "number"
        },
        "publicationKind": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "relatedWorkSlugs": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "releaseDate": {
      "type": "string"
    },
    "releaseDisplayState": {
      "type": "string"
    },
    "releaseStatus": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "format",
    "canonStatus",
    "releaseDisplayState"
  ],
  "title": "Work",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/star-wars-the-mandalorian-the-art-imagery-collectors-edition-volume-two.json
{
  "bookType": "referenceBook",
  "canonStatus": "canon",
  "displayTitle": "The Mandalorian - The Art & Imagery Collector's Edition, Volume Two",
  "editions": [
    {
      "imprint": "Titan Comics",
      "isPrimary": true,
      "kind": "print",
      "onsale": "2021-02-02T00:00:00.000Z"
    }
  ],
  "format": "book",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2021-02-02T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-the-mandalorian-the-art-imagery-collectors-edition-volume-two",
  "synopsis": "A collection of art from the end credits of Star Wars: the Mandalorian chapters 5-8 and more!Includes art as seen in the hit Disney+ TV series directed by Dave Filoni and John Favreau, starring Pedro Pascal, as illustrated by some of Lucasfilm's finest artists",
  "title": "Star Wars: The Mandalorian - The Art & Imagery Collector's Edition, Volume Two"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/thrawn-alliances-comics-thrawn-alliances-1.json
{
  "canonStatus": "canon",
  "displayTitle": "Thrawn: Alliances #1",
  "era": "ageOfRebellion",
  "format": "periodicalIssue",
  "parentWorkSlug": "thrawn-alliances-comics",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2018-07-24T00:00:00.000Z",
  "releaseDisplayState": "upcoming",
  "slug": "thrawn-alliances-comics-thrawn-alliances-1",
  "synopsis": "Grand Admiral Thrawn and Darth Vader ally against a threat to the Empire in this new novel from bestselling author Timothy Zahn.\n\"I have sensed a disturbance in the Force.\"\nOminous words under any circumstances, but all the more so when uttered by Emperor Palpatine. On Batuu, at the edges of the Unknown Regions, a threat to the Empire is taking root&mdash;its existence little more than a glimmer, its consequences as yet unknowable. But it is troubling enough to the Imperial leader to warrant investigation by his most powerful agents: ruthless enforcer Lord Darth Vader and brilliant strategist Grand Admiral Thrawn. Fierce rivals for the emperor's favor, and outspoken adversaries on Imperial affairs&mdash;including the Death Star project&mdash;the formidable pair seem unlikely partners for such a crucial mission. But the Emperor knows it's not the first time Vader and Thrawn have joined forces. And there's more behind his royal command than either man suspects.\nIn what seems like a lifetime ago, General Anakin Skywalker of the Galactic Republic, and Commander Mitth'raw'nuruodo, officer of the Chiss Ascendancy, crossed paths for the first time. One on a desperate personal quest, the other with motives unknown&hellip;and undisclosed. But facing a gauntlet of dangers on a far-flung world, they forged an uneasy alliance&mdash;neither remotely aware of what their futures held in store.\nNow, thrust together once more, they find themselves bound again for the planet where they once fo",
  "title": "Thrawn: Alliances #1"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-adventures-shadow-of-vader-s-castle-2020-1.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Cavan Scott",
      "role": "writer",
      "slug": "cavan-scott"
    },
    {
      "name": "Derek Charm",
      "role": "artist",
      "slug": "derek-charm"
    },
    {
      "name": "Nick Brokenshire",
      "role": "artist",
      "slug": "nick-brokenshire"
    },
    {
      "name": "Nicoletta Baldari",
      "role": "artist",
      "slug": "nicoletta-baldari"
    }
  ],
  "displayTitle": "Adventures: Shadow of Vader's Castle #1",
  "era": "newRepublic",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 4
  },
  "parentWorkSlug": "star-wars-adventures-shadow-of-vader-s-castle-2020",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2020-11-04T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-adventures-shadow-of-vader-s-castle-2020-1",
  "synopsis": "Continuing the Vader’s Castle series, this single-issue comic proves that even after good conquers evil, Vader’s looming shadow continues to haunt those who dare trespass on his domain long after his death.",
  "title": "Star Wars Adventures: Shadow of Vader's Castle #1"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/age-of-resistance-general-hux-2019-1.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Leonard Kirk",
      "role": "penciler",
      "slug": "leonard-kirk"
    },
    {
      "name": "Cory Hamscher",
      "role": "inker",
      "slug": "cory-hamscher"
    },
    {
      "name": "Mark Paniccia",
      "role": "editor",
      "slug": "mark-paniccia"
    },
    {
      "name": "Guru Efx",
      "role": "colorist",
      "slug": "guru-efx"
    },
    {
      "name": "Tom Taylor",
      "role": "writer",
      "slug": "tom-taylor"
    },
    {
      "name": "Bria Lavorgna",
      "role": "writer",
      "slug": "bria-lavorgna"
    },
    {
      "name": "Vc Travis Lanham",
      "role": "letterer",
      "slug": "vc-travis-lanham"
    },
    {
      "name": "Phil Noto",
      "role": "coverArtist",
      "slug": "phil-noto"
    }
  ],
  "displayTitle": "Age Of Resistance: General Hux (2019) #1",
  "format": "periodicalIssue",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDisplayState": "announced",
  "slug": "age-of-resistance-general-hux-2019-1",
  "title": "Age Of Resistance: General Hux (2019) #1"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/poe-dameron-24.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Charles Soule",
      "role": "writer",
      "slug": "charles-soule"
    },
    {
      "name": "Angel Unzueta",
      "role": "artist",
      "slug": "angel-unzueta"
    },
    {
      "name": "Joe Caramagna",
      "role": "artist",
      "slug": "joe-caramagna"
    },
    {
      "name": "Arif Pianto",
      "role": "artist",
      "slug": "arif-pianto"
    },
    {
      "name": "Phil Noto",
      "role": "artist",
      "slug": "phil-noto"
    },
    {
      "name": "Angel Unzueta",
      "role": "inker",
      "slug": "angel-unzueta"
    },
    {
      "name": "Angel Unzueta",
      "role": "penciler",
      "slug": "angel-unzueta"
    },
    {
      "name": "Phil Noto",
      "role": "coverArtist",
      "slug": "phil-noto"
    },
    {
      "name": "Vc Joe Caramagna",
      "role": "letterer",
      "slug": "vc-joe-caramagna"
    },
    {
      "name": "Jordan D. White",
      "role": "editor",
      "slug": "jordan-d-white"
    },
    {
      "name": "Arif Pianto",
      "role": "colorist",
      "slug": "arif-pianto"
    }
  ],
  "displayTitle": "Poe Dameron #24: Legend Found, Part V",
  "era": "riseOfTheFirstOrder",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 34
  },
  "parentWorkSlug": "poe-dameron",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2018-02-14T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "poe-dameron-24",
  "synopsis": "Lor San Tekka has been captured…again! And it's up to Black Squadron to save him. Meanwhile, Terex has his own plans in motion…to finally free himself from the grasp of the First Order!",
  "title": "Poe Dameron #24: Legend Found, Part V"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical/the-phantom-menace-25th-anniversary-special-2024.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Greg Pak",
      "role": "writer",
      "slug": "greg-pak"
    },
    {
      "name": "Will Sliney",
      "role": "artist",
      "slug": "will-sliney"
    }
  ],
  "displayTitle": "The Phantom Menace 25th Anniversary Special",
  "era": "fallOfTheJedi",
  "format": "periodical",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2024-05-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "the-phantom-menace-25th-anniversary-special-2024",
  "synopsis": "CELEBRATING THE 25TH ANNIVERSARY OF THE PHANTOM MENACE WITH AN ALL-NEW STORY! Explore the earliest days and secret inner life of ANAKIN SKYWALKER with never-before-seen, revelatory stories set before, after and between the scenes of the classic movie! Featuring the dream of a JEDI, the gift of a TUSKEN RAIDER, the heart of a GUNGAN, the ache of a mother and the horror of a hero!",
  "title": "The Phantom Menace 25th Anniversary Special"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/william-shakespeares-the-merry-rise-of-skywalker-star-wars-part-the-ninth.json
{
  "bookType": "other",
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Ian Doescher",
      "role": "writer",
      "slug": "ian-doescher"
    }
  ],
  "displayTitle": "William Shakespeare's The Merry Rise of Skywalker: Star Wars Part the Ninth",
  "editions": [
    {
      "imprint": "Quirk Books",
      "isPrimary": true,
      "kind": "print",
      "onsale": "2020-07-28T00:00:00.000Z"
    }
  ],
  "format": "book",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2020-07-28T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "william-shakespeares-the-merry-rise-of-skywalker-star-wars-part-the-ninth",
  "synopsis": "William Shakespeare's The Merry Rise of Skywalker is a non-canon junior novelization of Star Wars: The Rise of Skywalker. Written by Ian Doescher in the style of William ShakespeareComplete your collection of the William Shakespeare's Star Wars® series and experience the blockbuster finale to the Star Wars® saga in a brand-new way, here reimagined as though it had been penned by the Bard of Avon.As our story opens, a sea of troubles threatens the valiant Resistance, who are pursued by the sound and fury of the vile First Order. Can Rey, Poe, Finn, Rose, BB-8, Chewbacca, and their allies overcome such toil and trouble? Shall Kylo Ren be proven fortune's fool or master of his fate? What will become of the House of Skywalker? And is all well that ends wellAuthentic meter, stage directions, reimagined movie scenes and dialogue, and hidden Easter eggs will entertain and impress fans of Star Wars® and Shakespeare alike. Every scene and character from the film appears in the book, along with twenty woodcut-style illustrations that depict an Elizabethan version of the Star Wars® galaxy.[",
  "title": "William Shakespeare's The Merry Rise of Skywalker: Star Wars Part the Ninth"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-insider-insider-158.json
{
  "canonStatus": "canon",
  "displayTitle": "Insider #158",
  "format": "periodicalIssue",
  "parentWorkSlug": "star-wars-insider",
  "periodical": {
    "publicationKind": "magazine"
  },
  "releaseDisplayState": "announced",
  "slug": "star-wars-insider-insider-158",
  "title": "Insider #158"
}
